# Generated by Django 2.2.1 on 2019-06-26 05:17

import city.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hash_tag', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='도시 이름')),
                ('main_img', models.ImageField(upload_to=city.models.city_img_path, verbose_name='메인 이미지')),
                ('hash_tag_set', models.ManyToManyField(related_name='city_hash_tag_set', to='hash_tag.HashTag', verbose_name='해시 태그')),
            ],
        ),
    ]
