# Generated by Django 2.2.1 on 2019-05-23 02:52

from django.db import migrations, models
import django.db.models.deletion
import trip_info.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TripInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성시간')),
                ('last_modified_at', models.DateTimeField(auto_now=True, verbose_name='최근 수정시간')),
                ('main_img', models.ImageField(upload_to=trip_info.models.trip_info_img_path, verbose_name='메인 이미지')),
            ],
        ),
        migrations.CreateModel(
            name='TripInfoDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='내용')),
                ('image', models.ImageField(upload_to=trip_info.models.trip_info_detail_img_path, verbose_name='이미지')),
                ('trip_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trip_info.TripInfo', verbose_name='원게시물')),
            ],
        ),
        migrations.CreateModel(
            name='TripInfoComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='댓글 내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성시간')),
                ('last_modified_at', models.DateTimeField(auto_now=True, verbose_name='최근 수정시간')),
                ('trip_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trip_info.TripInfo', verbose_name='원게시물')),
            ],
        ),
    ]
