# Generated by Django 2.2 on 2019-05-09 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import trip_info.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hash_tag', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TripInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성시간')),
                ('last_modified_at', models.DateTimeField(auto_now=True, verbose_name='최근 수정시간')),
                ('page_cnt', models.PositiveSmallIntegerField(verbose_name='페이지 수')),
                ('main_img', models.ImageField(upload_to=trip_info.models.trip_info_img_path, verbose_name='메인 이미지')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
        ),
        migrations.CreateModel(
            name='TripInfoDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='내용')),
                ('image', models.ImageField(upload_to=trip_info.models.trip_info_detail_img_path, verbose_name='이미지')),
                ('trip_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trip_info.TripInfo', verbose_name='원게시물')),
            ],
        ),
        migrations.CreateModel(
            name='TripInfoComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='댓글 내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성시간')),
                ('last_modified_at', models.DateTimeField(auto_now=True, verbose_name='최근 수정시간')),
                ('trip_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trip_info.TripInfo', verbose_name='원게시물')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
        ),
        migrations.AddField(
            model_name='tripinfo',
            name='comment_user_set',
            field=models.ManyToManyField(related_name='comment_trip_info_set', through='trip_info.TripInfoComment', to=settings.AUTH_USER_MODEL, verbose_name='댓글 유저'),
        ),
        migrations.AddField(
            model_name='tripinfo',
            name='hash_tag_set',
            field=models.ManyToManyField(related_name='trip_info_set', to='hash_tag.HashTag', verbose_name='해시 태그'),
        ),
        migrations.AddField(
            model_name='tripinfo',
            name='like_user_set',
            field=models.ManyToManyField(related_name='like_trip_info_set', to=settings.AUTH_USER_MODEL, verbose_name='좋아요 유저'),
        ),
    ]
