# Generated by Django 2.2.1 on 2019-05-23 02:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hash_tag', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trip_info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripinfocomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자'),
        ),
        migrations.AddField(
            model_name='tripinfo',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자'),
        ),
        migrations.AddField(
            model_name='tripinfo',
            name='comment_user_set',
            field=models.ManyToManyField(related_name='comment_trip_info_set', through='trip_info.TripInfoComment', to=settings.AUTH_USER_MODEL, verbose_name='댓글 유저'),
        ),
        migrations.AddField(
            model_name='tripinfo',
            name='hash_tag_set',
            field=models.ManyToManyField(related_name='trip_info_set', to='hash_tag.HashTag', verbose_name='해시 태그'),
        ),
        migrations.AddField(
            model_name='tripinfo',
            name='like_user_set',
            field=models.ManyToManyField(related_name='like_trip_info_set', to=settings.AUTH_USER_MODEL, verbose_name='좋아요 유저'),
        ),
    ]
