# Generated by Django 2.2 on 2019-05-16 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip_info', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripinfo',
            name='page_cnt',
        ),
    ]
