# Generated by Django 2.2.1 on 2019-06-26 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0001_initial'),
        ('trip_info', '0002_auto_20190523_0252'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripinfo',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='city.City', verbose_name='도시'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tripinfo',
            name='hash_tag_set',
            field=models.ManyToManyField(related_name='trip_info_hash_tag_set', to='hash_tag.HashTag', verbose_name='해시 태그'),
        ),
    ]
