# Generated by Django 2.2.1 on 2019-06-26 05:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_info', '0003_auto_20190626_0517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripinfo',
            name='comment_user_set',
            field=models.ManyToManyField(blank=True, related_name='comment_trip_info_set', through='trip_info.TripInfoComment', to=settings.AUTH_USER_MODEL, verbose_name='댓글 유저'),
        ),
        migrations.AlterField(
            model_name='tripinfo',
            name='like_user_set',
            field=models.ManyToManyField(blank=True, related_name='like_trip_info_set', to=settings.AUTH_USER_MODEL, verbose_name='좋아요 유저'),
        ),
    ]
