# Generated by Django 2.2.1 on 2019-07-17 06:53

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import trip_package.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('city', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('guide', '0001_initial'),
        ('hash_tag', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('sub_title', models.CharField(max_length=100, verbose_name='제목')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성시간')),
                ('last_modified_at', models.DateTimeField(auto_now=True, verbose_name='최근 수정시간')),
                ('address', models.CharField(max_length=191, verbose_name='메인주소')),
                ('price', models.PositiveIntegerField(verbose_name='가격')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='city.City', verbose_name='도시')),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guide.Guide', verbose_name='가이드')),
                ('hash_tag_set', models.ManyToManyField(related_name='trip_package_hash_tag_set', to='hash_tag.HashTag', verbose_name='해시 태그')),
                ('like_user_set', models.ManyToManyField(blank=True, related_name='like_trip_package_set', to=settings.AUTH_USER_MODEL, verbose_name='좋아요 유저')),
            ],
        ),
        migrations.CreateModel(
            name='TripPackageReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(max_length=1, validators=[django.core.validators.RegexValidator('^[1,5]$')], verbose_name='평점')),
                ('image', models.ImageField(blank=True, default='', upload_to=trip_package.models.trip_package_review_img_path, verbose_name='이미지')),
                ('text', models.TextField(blank=True, verbose_name='리뷰 내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성시간')),
                ('last_modified_at', models.DateTimeField(auto_now=True, verbose_name='최근 수정시간')),
                ('trip_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trip_package.TripPackage', verbose_name='상품')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
        ),
        migrations.CreateModel(
            name='TripPackageMainImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=trip_package.models.trip_package_main_img_path, verbose_name='이미지')),
                ('trip_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trip_package.TripPackage', verbose_name='상품')),
            ],
        ),
        migrations.CreateModel(
            name='TripPackageDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='', upload_to=trip_package.models.trip_package_detail_img_path, verbose_name='이미지')),
                ('text', models.TextField(blank=True, default='', verbose_name='내용')),
                ('trip_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trip_package.TripPackage', verbose_name='상품')),
            ],
        ),
        migrations.CreateModel(
            name='TripPackageAddition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='제목')),
                ('text', models.TextField(blank=True, default='', verbose_name='내용')),
                ('trip_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trip_package.TripPackage', verbose_name='상품')),
            ],
        ),
        migrations.AddField(
            model_name='trippackage',
            name='review_user_set',
            field=models.ManyToManyField(blank=True, related_name='trip_package_review_set', through='trip_package.TripPackageReview', to=settings.AUTH_USER_MODEL, verbose_name='리뷰 유저'),
        ),
    ]
