# Generated by Django 2.2.1 on 2019-07-24 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_package', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trippackage',
            name='sub_title',
            field=models.CharField(max_length=100, verbose_name='부제'),
        ),
    ]
